# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wealthmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('name', models.CharField(max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='opportunitysearch',
            name='industry',
        ),
        migrations.AddField(
            model_name='opportunitysearch',
            name='industries',
            field=models.ManyToManyField(blank=True, null=True, to='wealthmap.Industry', verbose_name='industries'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='benefit_types',
            field=models.ManyToManyField(blank=True, to='wealthmap.BenefitType', verbose_name='benefit types'),
        ),
        migrations.AddField(
            model_name='opportunitysearch',
            name='benefit_types',
            field=models.ManyToManyField(to='wealthmap.BenefitType', verbose_name='benefit types'),
        ),
    ]
