# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0002_auto_20160715_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitysearch',
            name='industries',
            field=models.ManyToManyField(to='wealthmap.Industry', verbose_name='industries'),
        ),
    ]
