# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0002_auto_20161007_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='state',
        ),
        migrations.RemoveField(
            model_name='opportunitysearch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='opportunitysearch',
            name='state',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='existing_business',
            field=models.CharField(blank=True, choices=[('existing', 'existing business'), ('new', 'new business')], max_length=8, null=True, verbose_name='does this require a business already exist or not?'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='personal_investment',
            field=models.BooleanField(verbose_name='requires personal investment'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='purposes',
            field=models.ManyToManyField(blank=True, help_text='leave blank if none apply', to='wealthmap.Purpose', verbose_name='purposes'),
        ),
    ]
