# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0002_auto_20160203_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='application_deadline',
            field=models.DateTimeField(),
        ),
    ]
