# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0003_auto_20160207_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
