# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0003_auto_20160627_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('order',), 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='opportunitysearch',
            options={'verbose_name': 'Opportunity Search', 'verbose_name_plural': 'Opportunity Searches'},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='purpose',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='purposes',
            field=models.ManyToManyField(to='wealthmap.Purpose', verbose_name='purposes'),
        ),
    ]
