# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0003_auto_20161027_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitysearch',
            name='benefit_types',
        ),
    ]
