# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0004_auto_20160627_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='wealthmap.Purpose', verbose_name='purposes'),
        ),
    ]
