# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0005_auto_20160627_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitysearch',
            old_name='industries',
            new_name='industry',
        ),
    ]
