# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0005_auto_20161028_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitysearch',
            name='existing_business',
            field=models.CharField(blank=True, choices=[('existing', 'existing business'), ('new', 'new business'), ('', 'either')], max_length=8, null=True, verbose_name='What stage are you at?'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='industries',
            field=models.ManyToManyField(to='wealthmap.Industry', verbose_name='What type of business are you?'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='personal_investment',
            field=models.BooleanField(verbose_name='Are you investing personal money?'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='purposes',
            field=models.ManyToManyField(to='wealthmap.Purpose', verbose_name='What are you looking for?'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='small_business',
            field=models.BooleanField(verbose_name='Are you a small business?'),
        ),
    ]
