# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0006_auto_20161214_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='description',
            field=models.CharField(default='update me', max_length=255),
            preserve_default=False,
        ),
    ]
