# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0006_auto_20160628_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitysearch',
            old_name='purpose',
            new_name='purposes',
        ),
    ]
