# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0007_auto_20160628_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitysearch',
            name='existing_business',
            field=models.CharField(blank=True, choices=[('existing', 'existing business'), ('new', 'new business')], max_length=8, null=True, verbose_name='existing business'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='purposes',
            field=models.ManyToManyField(to='wealthmap.Purpose', verbose_name='purposes'),
        ),
    ]
