# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0007_purpose_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitysearch',
            name='existing_business',
            field=models.CharField(choices=[('existing', 'existing business')], default='new', max_length=8, verbose_name='What stage are you at?'),
            preserve_default=False,
        ),
    ]
