# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0008_auto_20160630_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampleopportunity',
            name='description',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
