# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0008_auto_20161214_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='existing_business',
            field=models.CharField(blank=True, choices=[('existing', 'Existing business'), ('new', 'New business'), ('', 'either')], max_length=8, null=True, verbose_name='this opportunity applies to'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='existing_business',
            field=models.CharField(choices=[('existing', 'Existing business'), ('new', 'New business')], default='Unspecified', max_length=8, verbose_name='What stage are you at?'),
        ),
    ]
