# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealthmap', '0013_auto_20160317_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitysearch',
            name='email',
        ),
    ]
