# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 20:39
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='postal_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
