# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0004_auto_20160207_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both'), ('other', 'Other')], max_length=6)),
                ('years_in_business', models.IntegerField(verbose_name='years_in_business')),
                ('investing_own_money', models.BooleanField(verbose_name='investing_own_money')),
                ('age', models.IntegerField(verbose_name='age')),
                ('employees', models.IntegerField(verbose_name='employees')),
                ('annual_revenue', models.IntegerField(verbose_name='annual_revenue')),
                ('location', models.CharField(choices=[('anywhere_in_pr', 'Cualquier municipio'), ('adjuntas', 'Adjuntas'), ('aguada', 'Aguada'), ('aguadilla', 'Aguadilla'), ('aguas_buenas', 'Aguas Buenas'), ('aibonito', 'Aibonito'), ('anasco', 'Añasco'), ('arecibo', 'Arecibo'), ('arroyo', 'Arroyo'), ('barceloneta', 'Barceloneta'), ('barranquitas', 'Barranquitas'), ('bayamon', 'Bayamón'), ('cabo_rojo', 'Cabo Rojo'), ('caguas', 'Caguas'), ('camuy', 'Camuy'), ('canovanas', 'Canóvanas'), ('carolina', 'Carolina'), ('catano', 'Cataño'), ('cayey', 'Cayey'), ('ceiba', 'Ceiba'), ('ciales', 'Ciales'), ('cidra', 'Cidra'), ('coamo', 'Coamo'), ('comerio', 'Comerio'), ('corozal', 'Corozal'), ('culebra', 'Culebra'), ('dorado', 'Dorado'), ('fajardo', 'Fajardo'), ('florida', 'Florida'), ('guanica', 'Guánica'), ('guayama', 'Guayama'), ('guayanilla', 'Guayanilla'), ('guaynabo', 'Guaynabo'), ('gurabo', 'Gurabo'), ('hatillo', 'Hatillo'), ('hormigueros', 'Hormigueros'), ('humacao', 'Humacao'), ('isabela', 'Isabela'), ('jayuya', 'Jayuya'), ('juana_diaz', 'Juana Diaz'), ('juncos', 'Juncos'), ('lajas', 'Lajas'), ('lares', 'Lares'), ('las_marias', 'Las Marías'), ('las_piedras', 'Las Piedras'), ('loiza', 'Loíza'), ('luquillo', 'Luquillo'), ('manati', 'Manatí'), ('maricao', 'Maricao'), ('maunabo', 'Maunabo'), ('mayaguez', 'Mayagüez'), ('moca', 'Moca'), ('morovis', 'Morovis'), ('naguabo', 'Naguabo'), ('naranjito', 'Naranjito'), ('orocovis', 'Orocovis'), ('patillas', 'Patillas'), ('penuelas', 'Penuelas'), ('ponce', 'Ponce'), ('quebradillas', 'Quebradillas'), ('rincon', 'Rincón'), ('rio_grande', 'Río Grande'), ('sabana_grande', 'Sabana Grande'), ('salinas', 'Salinas'), ('san_german', 'San German'), ('san_juan', 'San Juan'), ('san_lorenzo', 'San Lorenzo'), ('san_sebastian', 'San Sebastian'), ('santa_isabel', 'Santa Isabel'), ('toa_alta', 'Toa Alta'), ('toa_baja', 'Toa Baja'), ('trujillo_alto', 'Trujillo Alto'), ('utuado', 'Utuado'), ('vega_alta', 'Vega Alta'), ('vega_baja', 'Vega Baja'), ('vieques', 'Vieques'), ('villalba', 'Villalba'), ('yabucoa', 'Yabucoa'), ('yauco', 'Yauco')], max_length=255)),
                ('entity_types', models.CharField(choices=[('any', 'Cualquier'), ('non_profit', 'Organización sin fines de lucro'), ('for_profit', 'Corporación o Asociación con fines de lucro '), ('sole_proprietor', 'Individuo (DBA-HNC)'), ('cooperative', 'Cooperativa')], max_length=255)),
                ('industries', models.CharField(choices=[('any', 'Cualquiera'), ('11', '11 - Agricultura, Silvicultura, Caza y Pesca'), ('21', '21 - Extracción de Gas y Petróleo'), ('22', '22 - Utilidades'), ('23', '23 - Construcción'), ('31-33', '31-33 Manufactura'), ('42', '42 - Comercio al por mayor'), ('44-45', '44-45 - Comercio al por menor'), ('48-49', '48-49 - Transporte y Almacén'), ('51', '51 - Información'), ('52', '52 - Finanzas y Seguros'), ('53', '53 - Bienes Raíces, Alquiler y Arrendamiento'), ('54', '54 - Servicios profesionales, científicos y técnicos'), ('56', '56 - Administración y apoyo, central de desechos y servicios de reparación'), ('61', '61 - Servicios educativos'), ('62', '62 - Cuidados de salud y asistencia social'), ('71', '71 - Artes, Entretenimiento y Recreación'), ('72', '72 - Alojamiento, Servicios de Alimentos y Lugares para Beber'), ('81', '81 - Otros Servicios (exceptuando la administración pública)'), ('92', '92 - Administración Pública'), ('other', 'Otra')], max_length=255)),
                ('demographics', models.CharField(choices=[('any', 'cualquiera'), ('student', 'estudiante'), ('veteran', 'veterano'), ('minority', 'minoría')], max_length=255)),
                ('benefit_types', models.CharField(choices=[('incentive', 'Incentivos'), ('loan', 'Créditos'), ('grant', 'Becas'), ('reimbursement', 'Reembolsos'), ('expertise', 'Talleres'), ('financing', 'Financiamiento'), ('other', 'Otros')], max_length=255)),
                ('purpose', models.CharField(choices=[('anything', 'Cualquiera'), ('open_location', 'Abrir un Nuevo Local'), ('open_franchise', 'Abrir una Franquicia'), ('train_employees', 'Adiestrar Empleados'), ('working_capital', 'Capital de trabajo'), ('buy_equipment', 'Comprar Equipo'), ('buy_commercial_property', 'Comprar una propiedad comercial'), ('hire_employees', 'Contratar Empleados  / Pasantes'), ('start_business', 'Crear un Negocio'), ('export', 'Exportar'), ('export_products', 'Exportar productos'), ('export_services', 'Exportar servicios'), ('improve_commercial_property', 'Mejorar una propiedad comercial'), ('cinematographic_production', 'Producción Cinematográfica'), ('keep_employees', 'Retener empleados'), ('relocate_business', 'Reubicar un Negocio'), ('other', 'Otro (Por favor especifíca el propósito)')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Opportunity Searches',
                'verbose_name': 'Opportunity Search',
            },
        ),
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='mission',
            field=models.TextField(blank=True, verbose_name='mission'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, verbose_name='municipality'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='web',
            field=models.URLField(blank=True, max_length=255, verbose_name='web'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='additional_information',
            field=models.TextField(verbose_name='additional_information'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='age_max'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='age_min',
            field=models.IntegerField(verbose_name='age_min'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primerpeso.Agency', verbose_name='agency'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='agency_contact_email',
            field=models.EmailField(max_length=254, verbose_name='agency_contact_email'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='agency_contact_name',
            field=models.CharField(max_length=255, verbose_name='agency_contact_name'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='agency_contact_phone',
            field=models.CharField(max_length=255, verbose_name='agency_contact_phone'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='annual_revenue_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='annual_revenue_max'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='annual_revenue_min',
            field=models.IntegerField(verbose_name='annual_revenue_min'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='application_cost',
            field=models.IntegerField(verbose_name='application_cost'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='application_deadline'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='average_application_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='average_application_time'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='benefit_description',
            field=models.TextField(verbose_name='benefit_description'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='employees_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='employees_max'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='employees_min',
            field=models.IntegerField(verbose_name='employees_min'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='investing_own_money',
            field=models.BooleanField(verbose_name='investing_own_money'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='minimum_years_in_business',
            field=models.IntegerField(verbose_name='minimum_years_in_business'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='money_invested',
            field=models.CharField(max_length=255, verbose_name='money_invested'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='requirement',
            field=models.ManyToManyField(through='primerpeso.RequirementRelationship', to='primerpeso.Requirement', verbose_name='requirement'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cost',
            field=models.TextField(blank=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='link',
            field=models.TextField(blank=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='requirementrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='requirementrelationship',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='requirementrelationship',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primerpeso.Opportunity', verbose_name='opportunity'),
        ),
        migrations.AlterField(
            model_name='requirementrelationship',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primerpeso.Requirement', verbose_name='requirement'),
        ),
        migrations.AlterField(
            model_name='requirementrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
