# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0008_auto_20160301_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitysearch',
            old_name='entity_types',
            new_name='entity_type',
        ),
    ]
