# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 19:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0012_auto_20160315_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('any', 'Cualquiera'), ('11', '11 - Agricultura, Silvicultura, Caza y Pesca'), ('21', '21 - Extracción de Gas y Petróleo'), ('22', '22 - Utilidades'), ('23', '23 - Construcción'), ('31-33', '31-33 Manufactura'), ('42', '42 - Comercio al por mayor'), ('44-45', '44-45 - Comercio al por menor'), ('48-49', '48-49 - Transporte y Almacén'), ('51', '51 - Información'), ('52', '52 - Finanzas y Seguros'), ('53', '53 - Bienes Raíces, Alquiler y Arrendamiento'), ('54', '54 - Servicios profesionales, científicos y técnicos'), ('56', '56 - Administración y apoyo, central de desechos y servicios de reparación'), ('61', '61 - Servicios educativos'), ('62', '62 - Cuidados de salud y asistencia social'), ('71', '71 - Artes, Entretenimiento y Recreación'), ('72', '72 - Alojamiento, Servicios de Alimentos y Lugares para Beber'), ('81', '81 - Otros Servicios (exceptuando la administraciónpública)'), ('92', '92 - Administración Pública'), ('other', 'Otra')], max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='industry',
            field=models.CharField(choices=[('any', 'Cualquiera'), ('11', '11 - Agricultura, Silvicultura, Caza y Pesca'), ('21', '21 - Extracción de Gas y Petróleo'), ('22', '22 - Utilidades'), ('23', '23 - Construcción'), ('31-33', '31-33 Manufactura'), ('42', '42 - Comercio al por mayor'), ('44-45', '44-45 - Comercio al por menor'), ('48-49', '48-49 - Transporte y Almacén'), ('51', '51 - Información'), ('52', '52 - Finanzas y Seguros'), ('53', '53 - Bienes Raíces, Alquiler y Arrendamiento'), ('54', '54 - Servicios profesionales, científicos y técnicos'), ('56', '56 - Administración y apoyo, central de desechos y servicios de reparación'), ('61', '61 - Servicios educativos'), ('62', '62 - Cuidados de salud y asistencia social'), ('71', '71 - Artes, Entretenimiento y Recreación'), ('72', '72 - Alojamiento, Servicios de Alimentos y Lugares para Beber'), ('81', '81 - Otros Servicios (exceptuando la administraciónpública)'), ('92', '92 - Administración Pública'), ('other', 'Otra')], max_length=255, verbose_name='What industry is your business?'),
        ),
    ]
