# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 00:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0014_remove_opportunitysearch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitysearch',
            name='entity_type',
            field=models.CharField(choices=[('non_profit', 'Organización sin fines de lucro'), ('for_profit', 'Corporación o Asociación con fines de lucro '), ('sole_proprietor', 'Individuo (DBA-HNC)'), ('cooperative', 'Cooperativa')], max_length=255, verbose_name='What is the business structure?'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='industry',
            field=models.CharField(choices=[('11', '11 - Agricultura, Silvicultura, Caza y Pesca'), ('21', '21 - Extracción de Gas y Petróleo'), ('22', '22 - Utilidades'), ('23', '23 - Construcción'), ('31-33', '31-33 Manufactura'), ('42', '42 - Comercio al por mayor'), ('44-45', '44-45 - Comercio al por menor'), ('48-49', '48-49 - Transporte y Almacén'), ('51', '51 - Información'), ('52', '52 - Finanzas y Seguros'), ('53', '53 - Bienes Raíces, Alquiler y Arrendamiento'), ('54', '54 - Servicios profesionales, científicos y técnicos'), ('56', '56 - Administración y apoyo, central de desechos y servicios de reparación'), ('61', '61 - Servicios educativos'), ('62', '62 - Cuidados de salud y asistencia social'), ('71', '71 - Artes, Entretenimiento y Recreación'), ('72', '72 - Alojamiento, Servicios de Alimentos y Lugares para Beber'), ('81', '81 - Otros Servicios (exceptuando la administraciónpública)'), ('92', '92 - Administración Pública'), ('other', 'Otra')], max_length=255, verbose_name='What industry is your business?'),
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('adjuntas', 'Adjuntas'), ('aguada', 'Aguada'), ('aguadilla', 'Aguadilla'), ('aguas_buenas', 'Aguas Buenas'), ('aibonito', 'Aibonito'), ('anasco', 'Añasco'), ('arecibo', 'Arecibo'), ('arroyo', 'Arroyo'), ('barceloneta', 'Barceloneta'), ('barranquitas', 'Barranquitas'), ('bayamon', 'Bayamón'), ('cabo_rojo', 'Cabo Rojo'), ('caguas', 'Caguas'), ('camuy', 'Camuy'), ('canovanas', 'Canóvanas'), ('carolina', 'Carolina'), ('catano', 'Cataño'), ('cayey', 'Cayey'), ('ceiba', 'Ceiba'), ('ciales', 'Ciales'), ('cidra', 'Cidra'), ('coamo', 'Coamo'), ('comerio', 'Comerio'), ('corozal', 'Corozal'), ('culebra', 'Culebra'), ('dorado', 'Dorado'), ('fajardo', 'Fajardo'), ('florida', 'Florida'), ('guanica', 'Guánica'), ('guayama', 'Guayama'), ('guayanilla', 'Guayanilla'), ('guaynabo', 'Guaynabo'), ('gurabo', 'Gurabo'), ('hatillo', 'Hatillo'), ('hormigueros', 'Hormigueros'), ('humacao', 'Humacao'), ('isabela', 'Isabela'), ('jayuya', 'Jayuya'), ('juana_diaz', 'Juana Diaz'), ('juncos', 'Juncos'), ('lajas', 'Lajas'), ('lares', 'Lares'), ('las_marias', 'Las Marías'), ('las_piedras', 'Las Piedras'), ('loiza', 'Loíza'), ('luquillo', 'Luquillo'), ('manati', 'Manatí'), ('maricao', 'Maricao'), ('maunabo', 'Maunabo'), ('mayaguez', 'Mayagüez'), ('moca', 'Moca'), ('morovis', 'Morovis'), ('naguabo', 'Naguabo'), ('naranjito', 'Naranjito'), ('orocovis', 'Orocovis'), ('patillas', 'Patillas'), ('penuelas', 'Penuelas'), ('ponce', 'Ponce'), ('quebradillas', 'Quebradillas'), ('rincon', 'Rincón'), ('rio_grande', 'Río Grande'), ('sabana_grande', 'Sabana Grande'), ('salinas', 'Salinas'), ('san_german', 'San German'), ('san_juan', 'San Juan'), ('san_lorenzo', 'San Lorenzo'), ('san_sebastian', 'San Sebastian'), ('santa_isabel', 'Santa Isabel'), ('toa_alta', 'Toa Alta'), ('toa_baja', 'Toa Baja'), ('trujillo_alto', 'Trujillo Alto'), ('utuado', 'Utuado'), ('vega_alta', 'Vega Alta'), ('vega_baja', 'Vega Baja'), ('vieques', 'Vieques'), ('villalba', 'Villalba'), ('yabucoa', 'Yabucoa'), ('yauco', 'Yauco')], max_length=255), default=list, size=None, verbose_name='Where is your business located?'),
        ),
    ]
