# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 00:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0015_auto_20160318_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitysearch',
            name='purpose',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('open_location', 'Abrir un Nuevo Local'), ('open_franchise', 'Abrir una Franquicia'), ('train_employees', 'Adiestrar Empleados'), ('working_capital', 'Capital de trabajo'), ('buy_equipment', 'Comprar Equipo'), ('buy_commercial_property', 'Comprar una propiedad comercial'), ('hire_employees', 'Contratar Empleados  / Pasantes'), ('start_business', 'Crear un Negocio'), ('export', 'Exportar'), ('export_products', 'Exportar productos'), ('export_services', 'Exportar servicios'), ('improve_commercial_property', 'Mejorar una propiedad comercial'), ('cinematographic_production', 'Producción Cinematográfica'), ('keep_employees', 'Retener empleados'), ('relocate_business', 'Reubicar un Negocio'), ('other', 'Otro (Por favor especifíca el propósito)')], max_length=255), default=list, size=None, verbose_name='How would you use the incentive?'),
        ),
    ]
