# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0018_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Search Contact', 'verbose_name_plural': 'Search Contacts'},
        ),
    ]
