# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0020_auto_20160329_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='incorportated',
            new_name='incorporated',
        ),
        migrations.AlterField(
            model_name='opportunitysearch',
            name='investing_own_money',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Will the CEOs be investing money from their own pockets?'),
        ),
    ]
